### ISSUE TITLE
Cannot use require directive from registered transforms/preprocessors.

### ISSUE THREAD

**Issue by matthewlehner** [rails/sprockets#156]
This is coming from my experience with sprockets-es6, which is using the recommended  preprocessor/transform syntax rather than registering as an engine.

Calling `//=require somefile` will result in:

```ruby
Sprockets::FileNotFound: couldn't find file 'es5_file' with type 'text/ecmascript-6'
```

sprockets-es6 is registered like this:
```ruby
register_mime_type 'text/ecmascript-6', extensions: ['.es6'], charset: :unicode
register_transformer 'text/ecmascript-6', 'application/javascript', ES6
register_preprocessor 'text/ecmascript-6', DirectiveProcessor
register_engine '.es6', ES6
```

but changing to simple an engine fixes the behaviour:
```ruby
register_engine '.es6', ES6, mime_type: 'application/javascript'
```

I've opened another issue at TannerRogalsky/sprockets-es6#19, but it feels like this is an issue in the 3.x branch of Sprockets.

**Comment by rafaelfranca** [comment]
This is actually an issue with sprockets-rails. I had this same issue yesterday. The reason is, you `es5_file.es6` file is in the `Rails.assets.precompile` list while it should be `es5_file.js` there. Could you try with sprockets-rails master?

**Comment by rafaelfranca** [comment]
oops, I mean `same_file.es6` that should be `some_file.js` in the `Rails.assets.precompile` list.

**Comment by rafaelfranca** [comment]
You can see the test that I wrote yesterday to make sure this works here https://github.com/rails/sprockets/commit/3a7a5fe0784ffee272e80b2e474bfcd066a7203b

**Comment by matthewlehner** [comment]
Thanks! This does look right, and from the Rails perspective the issue is only happening for me during the `rake assets:precompile` process.

That said, I've reproduced it with some similar tests in the sprockets-es6 repo, however, these are running against sprockets 3.4.0. I'll check if these tests pass on the 3.x branch as it looks like the way that the built in processors are registered have changed from engines to transforms/preprocessors on master.

I'll do a bit more sleuthing!

**Comment by rafaelfranca** [comment]
It is an issue in the way sprockets-rails works that is fixed in its master version so I'm closing this one. Thanks

**Comment by matthewlehner** [comment]
@rafaelfranca I'd like to re-open this long-dead issue (is this okay?) I can open a new issue if that's preferable.
I've recently had some more time to dig in here and am getting the same error in a vanilla Rails app with the following gems:

```ruby
gem 'sprockets', '~> 4.0.0.beta2'
gem 'sprockets-rails', github: 'rails/sprockets-rails'
gem 'babel-transpiler', '~> 0.7.0'
```

To reproduce, clone https://github.com/matthewlehner/sprockets-es6-mime-failures

I've tried to keep this as minimal as possible, and have only added the required gems to compile es6 and renamed the JavaScript entry point to `app/assets/javscripts/application.es6`.

**Comment by rafaelfranca** [comment]
It is fine. I'll take a look.

**Comment by schneems** [comment]
Any luck?

**Comment by michaelherold** [comment]
I went through @matthewlehner's example app. It fails to find `jquery` through the `application.es6` file on Sprockets 4.0.0.beta2.

However, when you use sprockets master, it correctly finds the issue.

I did a bisect and discovered that the behavior was fixed with the changes from #255. Specifically, if I cherry-pick 4da21144 onto the v4.0.0.beta2 tag the example application works as expected.

@matthewlehner could you give that a try (or just try master) to see if it works for you as well?

**Comment by matthewlehner** [comment]
@michaelherold I think you're right! I tried this again yesterday in a different app and couldn't reproduce it, but still was still broken in the example app regardless of the version of Sprockets I was using – it _might_ have been a caching issue though, as I've noticed that the cached assets are not busted when options for the compiler are changed.
I'll give it a shot with Sprockets master and see what I can find.

**Comment by lifeiscontent** [comment]
@matthewd @schneems @rafaelfranca  any updates on this? Is this working as expected? I seem to be having the same issue, but inside of a middleman app using sprockets.

**Comment by matthewlehner** [comment]
Just tested this morning. Still experiencing this in Rails 5 with Sprockets 4 beta.2, however, it _seems_ to be fixed on master.

Perhaps another beta version could be released to get this working?

**Comment by schneems** [comment]
I released master with a few other fixes for 4.0.0.beta3. Give it a whirl. Let me know if the issue comes back.

**Comment by matthewlehner** [comment]
@schneems Thanks so much! 😻

Just watched your RailsConf talk about inheriting Sprockets and loved it. Thanks for the work on the 4.0 release so far!

**Comment by mtamhankar1** [comment]
I haven't done much testing or research on this, but I am reproducing this issue in beta3 and beta4. The main difference that I can see in my setup is that the require to es5 is coming from `application.es6.erb` as opposed to `application.es6`.

Has anyone else seen anything like this?
